/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#0f0069',
        'on-tertiary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#004b73',
        'on-primary-container': '#fdfcff',
        'inverse-primary': '#93ccff',
        'on-primary': '#ffffff',
        'surface-container': '#e5eeff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'primary-container': '#007bb9',
        'on-secondary-container': '#fffbff',
        'primary-fixed': '#cce5ff',
        tertiary: '#545c72',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#44546a',
        'on-secondary-fixed-variant': '#3323cc',
        'on-error-container': '#93000a',
        'on-tertiary-container': '#fefcff',
        background: '#f8f9ff',
        primary: '#006194',
        'secondary-fixed': '#e2dfff',
        'tertiary-fixed-dim': '#bec6e0',
        error: '#ba1a1a',
        'secondary-fixed-dim': '#c3c0ff',
        'tertiary-fixed': '#dae2fd',
        'primary-fixed-dim': '#93ccff',
        'inverse-surface': '#213145',
        'error-container': '#ffdad6',
        'surface-container-highest': '#d3e4fe',
        'surface-container-high': '#dce9ff',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#001d31',
        'inverse-on-surface': '#eaf1ff',
        'on-background': '#0b1c30',
        'on-tertiary-fixed-variant': '#3f465c',
        'tertiary-container': '#6c748b',
        'outline-variant': '#bfc7d2',
        secondary: '#4b41e1',
        'on-secondary': '#ffffff',
        surface: '#f8f9ff',
        'on-error': '#ffffff',
        'surface-tint': '#006398',
        'surface-container-low': '#eff4ff',
        'secondary-container': '#645efb',
        outline: '#707881',
        'surface-variant': '#d3e4fe',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        margin: '1rem',
        'space-2xl': '2rem',
        'space-sm': '0.5rem',
        'space-lg': '1rem',
        'space-md': '0.75rem',
        'margin-tablet': '1.5rem',
        'gutter-desktop': '1.5rem',
        'space-xs': '0.25rem',
        'gutter-tablet': '1.25rem',
        'space-xl': '1.5rem',
        gutter: '1rem',
        'margin-desktop': '2rem',
        'space-xxs': '0.125rem',
      },
      fontFamily: {
        'body-sm': ['Inter'],
        'body-md': ['Inter'],
        'title-md': ['Inter'],
        'label-sm': ['Inter'],
        'label-lg': ['Inter'],
        'metric-currency': ['Inter'],
        'headline-xl': ['Plus Jakarta Sans'],
        'label-md': ['Inter'],
        'headline-sm': ['Plus Jakarta Sans'],
        'body-lg': ['Inter'],
        'display-lg': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'metric-currency': ['20px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-xl': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'display-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
